name: Deploy on Vercel

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: publish
      run: |
            cd CHN.Blazor
            dotnet publish -c Release
    - uses: amondnet/vercel-action@v20.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORGID}}
        vercel-project-id: ${{ secrets.PROJECTID}}
        vercel-args: '--prod --confirm'
        working-directory: ./CHN.Blazor/bin/Release/net5.0/publish/wwwroot
